### ISSUE TITLE
Deadeye Slow-Mo Overide

### ISSUE THREAD

**Issue by ErikTheVking** [relaxtakenotes/deadeye#4]
I know there was a subject about this already, however, i am asking if there is any way you could overide the mods that are conflicting with the Deadeye Slow-Mo. Several mods like the FEAR bullet time work fine and do not conflict, so can't this mod do the same?

**Comment by ErikTheVking** [comment]
Edit: Without slow-mo is actually pretty cool and fun, so a toggle between slow-mo and normal time would be nice

**Comment by relaxtakenotes** [comment]
> Edit: Without slow-mo is actually pretty cool and fun, so a toggle between slow-mo and normal time would be nice

added
